name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: self-hosted   # 👈 tells GitHub to use your own runner
    # optionally you can add custom labels if you gave your runner labels
    # runs-on: [self-hosted, linux, my-server]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: PYTHONPATH=$(pwd) pytest

  build-and-publish-image:
    needs: build-and-test
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          file: poc-01/Dockerfile
          tags: gemini-poc-01:latest

